 MODULE ANNModule
   !Purpose: Train ANN and to evaluate ANN nodel response for a particular input

   !ydata -- the observables (1D array of size ndata) 
   !xdata -- input values in 1D form (1D array of size ndimensionsx*ndata)
   !ndimensionsx -- dimensionality of the independent variable space
   !ndata -- number of data points
   !nlayers -- number of layers in the ANN
   !nneuronperlayer -- Number of neuron in each layer (1D array of size nlayers)
   !weights -- weight given to each input in a neuron
   
   ! Weights are supplied by the user (or generated by the ANN training subroutine) in the 1D raw form 
   !     transpose of "weights" vector, which contains the weights of all the layers
   ![w(1,1) w(1,2) ....  w(1,m) w(2,1) w(2,2) ....  w(2,m) ..... w(n,1) w(n,2) ....  w(n,m) b(1) ... b(n)]
   ! These get transformed into the processed form
   !    _                            _
   !   |  w(1,1) w(1,2)  ...   w(1,m) |  
   !   |                              |  w(i,j) is the weight for the ith neuron acting on the jth element of the input
   ! W=|                              |  these are the weights for a particular layer I
   !   |                              |  each row corresponds to the weights for a particular neuron
   !   |                              |  n is the number of neurons in the layer I (nneuronperlayer(I))
   !   |_ w(n,1) w(n,1)  ...   w(n,m)_|  m is the dimensionality of input variables (ndimensionsx)
   !  and
   ! b=[b(1) b(2)  ..... b(m)]' is the bias vector for the neurons in the layer. Note that W and b are both in weights 
   !   vector
   
   !Data is supplied by the user in the 1D raw form
   !     transpose of [x(1,1) x(2,1) ....  x(m,1) w(1,2) x(2,2) ....  x(m,2) ..... x(1,p) x(2,p) ....  x(m,p)]
   ! These get transformed into the processed form
   !    _                            _
   !   |  x(1,1) x(1,2)  ...   x(1,p) |
   !   |                              |
   ! X=|                              |  these are the input data provided to the ANN
   !   |                              |  each column corresponds to data point
   !   |                              |  m is the dimensionality of input variables (ndimensionsx)
   !   |_ x(m,1) x(m,2)  ...   x(m,p)_|  p is the number of data points collected (ndata)
   
   !The dot product between W and a column j of X (i.e., the jth data point) corresponds to the input for 
   !each of the activation functions of the layer -- if the activation function F() acts on the result we
   !obtain a column vector which is the output from the layer for the jth data point
   
   !The dot product between W and X gives a matrix where each column is the input for the activation functions
   !of the layer for a data point. When F() operates on the resulting matrix we obtain the output for all data
   !points. Each column of this new matrix is the output for a data point from this layer
   
   !    _        _
   !   |  t(1,1)  |
   !   |          |
   ! T=|          |  these are ydata provided to ANN
   !   |          |  each element corresponds to an observable
   !   |          |  p is the number of data points collected (ndata)
   !   |_ t(p,1) _|

   USE VARIABLE_TYPE
   USE machinelearning
   USE Ecuyer_random
   USE OptimPackage
   USE StatisticsPackage
   IMPLICIT NONE
   
   INTEGER, PARAMETER :: MaxInputPerNeuron=100 !this also determines the dimension of x data
   INTEGER, PARAMETER :: MaxDataSize=MaxInputPerNeuron
   INTEGER, PARAMETER :: MaxNeuronPerLayer=20
   INTEGER, PARAMETER :: MaxWeightsPerLayer=MaxInputPerNeuron*MaxNeuronPerLayer
   INTEGER, PARAMETER :: MaxLayers=10
   !xxxxxxxxxxxxxxxxxxxxx
   TYPE NeuralNet
      !Data variables
      INTEGER :: ndimensionsx=0
      REAL(dp), DIMENSION(:), POINTER :: xdata=>NULL(),ydata=>NULL() !user stores all the data here (dimensions of xdata and ydata can be different)
      INTEGER :: nmaxdata=0 !capacity of xdata and ydata -- nmax_xydata>ndata and ndata can be increasing in a dynamical simulation
      INTEGER :: ndata=0 !number of data points stored in xdata and ydata
      REAL(dp), DIMENSION(:), POINTER :: xdata_stored=>NULL(),ydata_stored=>NULL()
      INTEGER :: nmaxdata_stored=0 !capacity of ydata_stored
      INTEGER, DIMENSION(:), POINTER :: xsignature=>NULL(),xstoredsignature=>NULL()
      INTEGER :: ndata_stored=0
      INTEGER :: ncritical_stored=0 !the amount of data which needs to be collected after which the ANN refit can be done
      REAL(dp), DIMENSION(:), POINTER :: xdata_selected=>NULL(),ydata_selected=>NULL() !contains data for a selected purpose, e.g. data assigned for training when training step is performed
      INTEGER :: ntraining=0,nvalidation=0,ntesting=0,nselected=0 !nselected is the number of points for a selected purpose, e.g., for training nselected is related to the size of ydata_selected
      INTEGER, DIMENSION(:), POINTER :: datapurpose=>NULL() !stores the purpose for which the data is supposed to be used (1=training, 2=testing, 3=validation)
      REAL(dp), DIMENSION(:), POINTER :: fdata_selected=>NULL() !ANN output is stored here
      REAL(dp) :: ftraining=0._dp,fvalidation=0._dp,ftesting=0._dp
      !ANN variables
      INTEGER :: nlayers=0,iseed=0
      INTEGER :: natoms=0,nweights=0,nbias=0,nweightsactive=0
      INTEGER :: OptimizationMode=2
      INTEGER, DIMENSION(:), POINTER :: nneuronperlayer=>NULL(),activationfunction=>NULL()
      INTEGER, DIMENSION(:), POINTER :: InteractionCount=>NULL()
      INTEGER, DIMENSION(:), POINTER :: SymmMap=>NULL()
      REAL(dp), DIMENSION(:), POINTER :: weights=>NULL()
      REAL(dp) :: OutlierMinDistance=0._dp
      LOGICAL :: IsFitted=.FALSE. !ANN has not been fitted so far
      LOGICAL :: TrackCorrelations=.FALSE.
      LOGICAL, DIMENSION(:,:), POINTER :: CorrelationNotConsidered=>NULL()
      LOGICAL, DIMENSION(:), POINTER :: InteractionIsActive=>NULL()
      !INTEGER :: ndegreesmin=100000,ndegreesmax=0
   END TYPE NeuralNet
   !xxxxxxxxxxxxxxxxxxxxx
   TYPE NeuralNetList
      TYPE(NeuralNetList), POINTER :: NextNeigh=>NULL(),PrevNeigh=>NULL()
      TYPE(NeuralNet), POINTER :: ANN=>NULL()
   END TYPE NeuralNetList
   !xxxxxxxxxxxxxxxxxxxxx
   TYPE(NeuralNetList), POINTER :: ANNList=>NULL()
   !xxxxxxxxxxxxxxxxxxxxx
   TYPE(NeuralNet), POINTER :: ActiveNeuralNet
   !xxxxxxxxxxxxxxxxxxxxx
   CONTAINS
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
   SUBROUTINE TrainANNBackpropagation(ANN,errorstatus)
   !Trains an ANN using the input data xdata and target data ydata
   !User inputs:
   !ydata is target data of size ndata
   !xdata is input data of size ndimensionsx * ndata
   !ndimensionsx is the dimensionality of x in each data point
   !ndata is the number of data points
   !nneuronperlayer is an array containing the number of neurons in each layer
   !nlayers is the number of layers in the ANN
   !weights is the weight vector which is automatically created by the code
   !nweights is the number of weights in the ANN
   !nbias is the number of bias in the ANN
   !ftraining and fvalidation are the fraction of data used for training and validation, respectively
   !datapurpose has value (1) training (2) testing and (3) validation
   !errorstatus is 0 (fitting was done normally), 1 (inadequate amount of data), 2 ()
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: purpose,errorstatus,i
      REAL(dp) :: RSq,maxerror
      CHARACTER :: crapchar
      
      !CALL CheckANNParameters() !makes sure that the code is able to cope with the sizes provided
      CALL FindSizeWeightsArray(ANN) !this will set weights to zero is the size of weights is changed
      ANN%weights=0._dp
      !IF (.NOT. ANN%IsFitted) CALL InitializeANNWeights(ANN) !if fitted used fitted weights for fast convergence
      CALL PartitionANNData(ANN)
      
      !Train the network
      purpose=1
      WRITE(6,*) "Training the network in TrainANNBackpropagation ..."
      CALL SelectData(ANN,purpose)!Collect the data into one array
      CALL GetActiveInteractions(ANN)
      
      IF (2*ANN%nweightsactive>ANN%nselected) THEN
         WRITE(6,*) "Err>> Too many parameters and few data points"
         errorstatus=4
         RETURN
      END IF
      
      CALL OptimizeANN(ANN)
      DO WHILE (EliminatedWeakInteractions(ANN,0.01_dp))
         CALL OptimizeANN(ANN)
         WRITE(6,*) "++++++++++++++++++++++++++++++"
      END DO
      ANN%fdata_selected=ANNOutput(ANN,ANN%xdata_selected,ANN%nselected,ANN%ndimensionsx)
      RSq= RSquared(ANN%ydata_selected,ANN%fdata_selected,ANN%nselected)
      WRITE(UNIT=6,FMT='(" ... RSquared value: ",F15.5)') RSq
      
      !find the maximum error
      maxerror=0._dp
      WRITE(6,*) "ActualActivationEnergy  PredictedActivationEnergy"
      DO i=1,ANN%nselected
         maxerror=MAX(maxerror,ABS(ANN%ydata_selected(i)-ANN%fdata_selected(i)))
         WRITE(6,*) ANN%ydata_selected(i),ANN%fdata_selected(i)
      END DO
      WRITE(6,*) "Maximum error is :",maxerror
      WRITE(6,*) "for total number of data points;",ANN%nselected
      
      IF (RSq<0.9) THEN
         WRITE(6,*) "... Poor fit obtained during training stage"
         errorstatus=1
         STOP
      END IF
      IF (ANN%TrackCorrelations) THEN
         CALL AddCorrelations(ANN,ANN%xdata_selected,ANN%ndimensionsx,ANN%nselected) !add which correlations are considered
         CALL DisplayCorrelations(ANN)
      END IF
      
      !Test the network
      purpose=2
      WRITE(6,*) "Testing the network in TrainANNBackpropagation ..."
      CALL SelectData(ANN,purpose)!Collect the data into one array
      ANN%fdata_selected=ANNOutput(ANN,ANN%xdata_selected,ANN%nselected,ANN%ndimensionsx)
      RSq= RSquared(ANN%ydata_selected,ANN%fdata_selected,ANN%nselected)
      WRITE(UNIT=6,FMT='(" ... RSquared value: ",F15.5)') RSq
      
      !find the maximum error
      maxerror=0._dp
      WRITE(6,*) "ActualActivationEnergy  PredictedActivationEnergy"
      DO i=1,ANN%nselected
         maxerror=MAX(maxerror,ABS(ANN%ydata_selected(i)-ANN%fdata_selected(i)))
         WRITE(6,*) ANN%ydata_selected(i),ANN%fdata_selected(i)
      END DO
      WRITE(6,*) "Maximum error is :",maxerror
      WRITE(6,*) "for total number of data points;",ANN%nselected
      
      IF (RSq<0.9) THEN
         WRITE(6,*) "... Poor fit obtained during testing stage"
         errorstatus=2
         STOP
      END IF
      !Validate the network
      purpose=3
      WRITE(6,*) "Validating the network in TrainANNBackpropagation ..."
      CALL SelectData(ANN,purpose)!Collect the data into one array
      ANN%fdata_selected=ANNOutput(ANN,ANN%xdata_selected,ANN%nselected,ANN%ndimensionsx)
      RSq= RSquared(ANN%ydata_selected,ANN%fdata_selected,ANN%nselected)
      WRITE(UNIT=6,FMT='(" ... RSquared value: ",F15.5)') RSq
      
      !find the maximum error
      maxerror=0._dp
      WRITE(6,*) "ActualActivationEnergy  PredictedActivationEnergy"
      DO i=1,ANN%nselected
         maxerror=MAX(maxerror,ABS(ANN%ydata_selected(i)-ANN%fdata_selected(i)))
         WRITE(6,*) ANN%ydata_selected(i),ANN%fdata_selected(i)
      END DO
      WRITE(6,*) "Maximum error is :",maxerror
      WRITE(6,*) "for total number of data points;",ANN%nselected
      
      IF (RSq<0.9) THEN
         WRITE(6,*) "... Poor fit obtained during validation stage"
         errorstatus=3
         STOP
      END IF
      
      ANN%IsFitted=.TRUE.
!WRITE(UNIT=6,FMT='("Type any key to continue:")',ADVANCE="NO")
!READ(*,*) crapchar
      STOP
   END SUBROUTINE TrainANNBackpropagation
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE DisplayError(ANN,tol,sclfac)
   !prints points with error greater than tol once fdata and ydata is available
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      REAL(dp), DIMENSION(:), POINTER :: ydata=>NULL()
      REAL(dp), DIMENSION(SIZE(ANN%xdata)) :: fdata
      REAL(dp) :: tol,error,sclfac,mean
      INTEGER :: i
      
      ydata=>ANN%ydata
      fdata=ANNOutput(ANN,ANN%xdata,ANN%ndata,ANN%ndimensionsx)
      DO i=1,ANN%ndata
         error=ABS(ydata(i)-fdata(i))*sclfac
         error=(ydata(i)-fdata(i))*sclfac
         !IF (error>tol) THEN
            WRITE(UNIT=6,FMT='(3F15.5)') ydata(i)*sclfac,fdata(i)*sclfac,error
         !END IF
      END DO
   END SUBROUTINE DisplayError
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE AddCorrelations(ANN,xdata,ndimensionsx,ndata)
   !add the correlations which have been considered in ANN fitting
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: ndimensionsx,ndata,idata,i,j,ndegrees
      REAL(dp), DIMENSION(ndimensionsx*ndata) :: xdata
      REAL(dp), DIMENSION(ndimensionsx) :: xdata1
      LOGICAL, DIMENSION(:,:), POINTER :: CorrelationNotConsidered=>NULL()
      
      CorrelationNotConsidered=>ANN%CorrelationNotConsidered
      DO idata=1,ndata
         xdata1=xdata(ndimensionsx*(idata-1)+1:ndimensionsx*idata)
         !ndegrees=0
         !DO i=1,ndimensionsx
         !   IF (xdata1(i)/=0._dp) ndegrees=ndegrees+1
         !END DO
         !ANN%ndegreesmax=MAX(ndegrees,ANN%ndegreesmax)
         !ANN%ndegreesmin=MIN(ndegrees,ANN%ndegreesmin)
         DO i=1,ANN%natoms
         !DO i=1,ndimensionsx-1
            DO j=i,ANN%natoms
               IF (xdata1(i)*xdata1(j)/=0._dp) CorrelationNotConsidered(i,j)=.FALSE. !correlation accounted
               !IF (xdata1(i)/=0._dp) CorrelationNotConsidered(i,j)=.FALSE.
            END DO
         END DO
      END DO
   END SUBROUTINE AddCorrelations
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE DisplayCorrelations(ANN)
   !shows which correlations have been considered in ANN
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: ndimensionsx,i,j
      LOGICAL, DIMENSION(:,:), POINTER :: CorrelationNotConsidered=>NULL()
      
      ndimensionsx=ANN%ndimensionsx
      CorrelationNotConsidered=>ANN%CorrelationNotConsidered
      WRITE(6,*) "Correlations that have not been considered ..."
      DO i=1,ANN%natoms
         DO j=1,i-1
            WRITE(UNIT=6,FMT='("   ")',ADVANCE="NO")
         END DO
         !WRITE(UNIT=6,FMT='(" - ")',ADVANCE="NO")
         DO j=i,ANN%natoms
            WRITE(UNIT=6,FMT='(L3)',ADVANCE="NO") CorrelationNotConsidered(i,j)
         END DO
         WRITE(6,*) ""
      END DO
   END SUBROUTINE DisplayCorrelations
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE StoreDataInANN(ANN,xdata,ydata,ndimensionsx,iprint,signature)
   !add a data point to the storage arrays in ANN and if the storage array is full then
   !obtain a new fit to the ANN
   !xdata and ydata contains new data that needs to be added to ANN
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: ndimensionsx,ndata_stored,errorstatus
      REAL(dp), DIMENSION(ndimensionsx) :: xdata
      REAL(dp) :: ydata,RSq
      INTEGER :: iprint1,i
      INTEGER, OPTIONAL :: iprint,signature
      LOGICAL :: NotSatisfied
      
      IF (PRESENT(iprint)) THEN
         iprint1=iprint
      ELSE
         iprint1=1
      END IF
      
      !IF (PRESENT(signature)) THEN
      !   IF (.NOT. DataIsUnique1(ANN,signature)) RETURN
      !ELSE
      !   WRITE(*,*) "This should not be called",PRESENT(signature)
      !   stop
      !   IF (.NOT. DataIsUnique(ANN,xdata,ydata,ndimensionsx)) RETURN
      !END IF
      
      IF (iprint1>0) THEN
         WRITE(UNIT=6,FMT='("Storing data in ANN: [")',ADVANCE="NO")
         DO i=1,ndimensionsx
            WRITE(UNIT=6,FMT='(F3.0)',ADVANCE="NO") xdata(i)
         END DO
         WRITE(UNIT=6,FMT='("]",F15.5)') ydata
      END IF
      write(*,*) "signature=",signature
      
      IF (iprint1>0) WRITE(6,*) "New data point found ... storing the data point in ANN ..."
      ndata_stored=ANN%ndata_stored
      IF (ndata_stored+1<=ANN%nmaxdata_stored) THEN
         ANN%xdata_stored(ndimensionsx*ndata_stored+1:ndimensionsx*(ndata_stored+1))=xdata
         ANN%ydata_stored(ndata_stored+1)=ydata
         IF (PRESENT(signature)) ANN%xstoredsignature(ndata_stored+1)=signature
         ndata_stored=ndata_stored+1
      ELSE
         WRITE(6,*) "Warning>> xdata_stored is full ... rejecting data"
         STOP
      END IF
      ANN%ndata_stored=ndata_stored
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... Number of data points stored in ANN is:",I6)') ANN%ndata_stored
      
      IF (ndata_stored>=ANN%ncritical_stored) THEN
!         NotSatisfied=.TRUE.
!         IF (ANN%IsFitted) THEN
!            ANN%fdata_selected=ANNOutput(ANN,ANN%xdata_stored,ANN%ndata_stored,ANN%ndimensionsx)
!            RSq= RSquared(ANN%ydata_stored,ANN%fdata_selected,ANN%ndata_stored)
!            WRITE(UNIT=6,FMT='(" ... RSquared value: ",F15.5)') RSq
!            IF (RSq<0.95) THEN
!               WRITE(6,*) "... Poor fit obtained during validation stage"
!            ELSE
!               WRITE(6,*) "... Good fit obtained during validation stage"
!               NotSatisfied=.FALSE. !no point in refitting ANN now
!            END IF
!         END IF
         CALL MoveStoredDataInANN(ANN)
!         IF (iprint1>0) THEN
!            WRITE(UNIT=6,FMT='("  ... Number of data points accessible for ANN fit:",I6)') ANN%ndata
!            WRITE(UNIT=6,FMT='("  ... Number of data points stored in ANN is:",I6)') ndata_stored
!            WRITE(UNIT=6,FMT='("  ... Number of data points has exceeded the ncritical number of data points:")')
!         END IF
!         IF (NotSatisfied) CALL TrainANNBackpropagation(ANN,errorstatus)
      END IF
   END SUBROUTINE StoreDataInANN
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION DataIsUnique1(ANN,signature)
   !TRUE when this data point is new to ANN, else it is false
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: signature,i
      INTEGER, DIMENSION(:), POINTER :: xsignature=>NULL()
      LOGICAL :: DataIsUnique1
      
      DataIsUnique1=.TRUE.
      xsignature=>ANN%xsignature
      DO i=1,ANN%ndata
         IF (xsignature(i)==signature) THEN
            DataIsUnique1=.FALSE.
            RETURN
         END IF
      END DO
      
      xsignature=>ANN%xstoredsignature
      DO i=1,ANN%ndata_stored
         IF (xsignature(i)==signature) THEN
            DataIsUnique1=.FALSE.
            RETURN
         END IF
      END DO
   END FUNCTION DataIsUnique1
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION DataIsUnique(ANN,xdata,ydata,ndimensionsx,iprint)
   !TRUE when this data point is new to ANN, else it is false
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: ndata,ndimensionsx,i
      REAL(dp), DIMENSION(ndimensionsx) :: xdata,w
      REAL(dp) :: distance,ydata
      REAL(dp), DIMENSION(:), POINTER :: xdata1=>NULL()
      LOGICAL :: DataIsUnique
      INTEGER :: iprint1,j
      INTEGER, OPTIONAL :: iprint
      
      IF (PRESENT(iprint)) THEN
         iprint1=iprint
      ELSE
         iprint1=1
      END IF
      
      DataIsUnique=.TRUE.
      xdata1=>ANN%xdata
      w=1._dp
      IF (iprint1>0) WRITE(6,*) "Comparing distance of new point to points in ANN ..."
      DO i=1,ANN%ndata
         distance=HammingDistance(xdata,xdata1(ndimensionsx*(i-1)+1:ndimensionsx*i),ndimensionsx,w)
         IF (iprint1>0) THEN
            WRITE(UNIT=6,FMT='("[")',ADVANCE="NO")
            DO j=1,ndimensionsx
               WRITE(UNIT=6,FMT='(F3.0)',ADVANCE="NO") xdata1(ndimensionsx*(i-1)+j)
            END DO
            WRITE(UNIT=6,FMT='("] Distance:",F15.5)') distance
         END IF
         IF (distance==0._dp) THEN
            DataIsUnique=.FALSE.
            RETURN
         END IF
      END DO
      
      xdata1=>ANN%xdata_stored
      DO i=1,ANN%ndata_stored
         distance=HammingDistance(xdata,xdata1(ndimensionsx*(i-1)+1:ndimensionsx*i),ndimensionsx,w)
         IF (iprint1>0) THEN
            WRITE(UNIT=6,FMT='("[")',ADVANCE="NO")
            DO j=1,ndimensionsx
               WRITE(UNIT=6,FMT='(F3.0)',ADVANCE="NO") xdata1(ndimensionsx*(i-1)+j)
            END DO
            WRITE(UNIT=6,FMT='("] Distance:",F15.5)') distance
         END IF
         IF (distance==0._dp) THEN
            DataIsUnique=.FALSE.
            RETURN
         END IF
      END DO
   END FUNCTION DataIsUnique
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE MoveStoredDataInANN(ANN)
   !this moves the data from the stored array into the data array
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: ndata,ndata_stored,ndimensionsx
      REAL(dp), DIMENSION(:), POINTER :: xdata,ydata,xdata_stored,ydata_stored
      
      ndata=ANN%ndata
      ndata_stored=ANN%ndata_stored
      xdata=>ANN%xdata
      ydata=>ANN%ydata
      xdata_stored=>ANN%xdata_stored
      ydata_stored=>ANN%ydata_stored
      ndimensionsx=ANN%ndimensionsx
      IF (ndata+ndata_stored<=ANN%nmaxdata) THEN
         xdata(ndimensionsx*ndata+1:ndimensionsx*(ndata+ndata_stored))= &
            xdata_stored(1:ndimensionsx*ndata_stored)
         ydata(ndata+1:ndata+ndata_stored)=ydata_stored(1:ndata_stored)
         ANN%xsignature(ndata+1:ndata+ndata_stored)=ANN%xstoredsignature(1:ndata_stored)
         ndata=ndata+ndata_stored
         ANN%ndata=ndata
         ANN%ndata_stored=0
      ELSE
         WRITE(6,*) "Cannot transfer the data into the data array"
         STOP
      END IF
   END SUBROUTINE MoveStoredDataInANN
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE ANNPrediction(ANN,xdata,ndimensionsx,fdata,errorstatus,signature,iprint)
   !gives the prediction from the ANN
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: ndimensionsx,errorstatus
      REAL(dp), DIMENSION(ndimensionsx) :: xdata
      REAL(dp) :: fdata,fdata_array(1)
      INTEGER :: iprint1,signature
      INTEGER, OPTIONAL :: iprint
      LOGICAL :: recovered
      
      IF (PRESENT(iprint)) THEN
         iprint1=iprint
      ELSE
         iprint1=1
      END IF
      
      !errorstatus=0
      !IF (.NOT. ANN%IsFitted) THEN !Fitting of ANN has not been done
      !   errorstatus=1
      !   IF (iprint1>0) WRITE(6,*) "ANN is not fitted hence no prediction"
      !   CALL RecoverDataFromANNTable(ANN,fdata,recovered,signature)
      !   IF (recovered) errorstatus=0
      !   RETURN
      !END IF
      !IF (DataIsOutlier(ANN,xdata,ndimensionsx)) THEN !data is outlier
      !   errorstatus=2
      !   IF (iprint1>0) WRITE(6,*) "Data is outlier hence no prediction"
      !   CALL RecoverDataFromANNTable(ANN,fdata,recovered,signature)
      !   IF (recovered) errorstatus=0
      !   RETURN
      !ELSE !find the output and store in fdata
         fdata_array=ANNOutput(ANN,xdata,1,ndimensionsx)
         fdata=fdata_array(1)
      !   IF (iprint1>0) WRITE(UNIT=6,FMT='("Prediction from ANN:",F15.5)') fdata
      !END IF
   END SUBROUTINE ANNPrediction
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE RecoverDataFromANNTable(ANN,fdata,recovered,signature)
   !tries to recover data from stored information in ANN table
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      REAL(dp) :: fdata
      LOGICAL :: recovered
      INTEGER :: signature,i
      INTEGER, DIMENSION(:), POINTER :: xsignature
      
      recovered=.FALSE.
      
      xsignature=>ANN%xsignature
      DO i=1,ANN%ndata
         recovered=(xsignature(i)==signature)
         IF (recovered) THEN
            fdata=ANN%ydata(i)
            RETURN
         END IF
      END DO
      
      xsignature=>ANN%xstoredsignature
      DO i=1,ANN%ndata_stored
         recovered=(xsignature(i)==signature)
         IF (recovered) THEN
            fdata=ANN%ydata_stored(i)
            RETURN
         END IF
      END DO
   END SUBROUTINE RecoverDataFromANNTable
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION DataIsOutlier(ANN,xdata,ndimensionsx,iprint)
   !checks whether data is an outlier based on the weights computed in ANN
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: ndimensionsx,errorstatus,i,ndata,ndegrees
      REAL(dp), DIMENSION(ndimensionsx) :: xdata,weights,weights1
      REAL(dp), DIMENSION(:), POINTER :: xdata1
      LOGICAL, DIMENSION(:,:), POINTER :: CorrelationNotConsidered
      REAL(dp) :: distance,distance1,OutlierMinDistance,maxweight,minweight,fdata_array(1)
      LOGICAL :: DataIsOutlier
      INTEGER :: iprint1,j,pos
      INTEGER, OPTIONAL :: iprint
      CHARACTER :: crapchar
      
      IF (PRESENT(iprint)) THEN
         iprint1=iprint
      ELSE
         iprint1=1
      END IF
      
      DataIsOutlier=.FALSE.
      CorrelationNotConsidered=>ANN%CorrelationNotConsidered
      pos=0
      DO i=1,ANN%natoms
         pos=pos+1
         DataIsOutlier= xdata(pos)/=0._dp .AND. CorrelationNotConsidered(i,i)
         IF (DataIsOutlier) RETURN
      END DO
      DO i=1,ANN%natoms-1
         DO j=i+1,ANN%natoms
            pos=pos+1
            DataIsOutlier= xdata(pos)/=0._dp .AND. CorrelationNotConsidered(i,j)
            IF (DataIsOutlier) RETURN
         END DO
      END DO
      
      !DO i=1,ndimensionsx-1
      !   DO j=i,ndimensionsx
      !      DataIsOutlier= (xdata(i)*xdata(j)/=0._dp) .AND. CorrelationNotConsidered(i,j) !correlation not accounted
      !      IF (DataIsOutlier) RETURN
      !   END DO
      !END DO
      !check if all effects are present
      
      !ndegrees=0
      !DO i=1,ndimensionsx
      !   IF (xdata(i)/=0._dp) ndegrees=ndegrees+1
      !END DO
      !IF (ndegrees<ANN%ndegreesmin .OR. ndegrees>ANN%ndegreesmax) RETURN
      
      !weights=ANN%weights(1:ndimensionsx) !this gives the importance of the variables
      !weights=ABS(weights)
      !maxweight=MAXVAL(weights)
      !minweight=MINVAL(ABS(weights))
      !weights=(weights-minweight)/(maxweight-minweight) !between 0 and 1
      !weights1=1._dp
      
      !xdata1=>ANN%xdata
      !ndata=ANN%ndata
      !OutlierMinDistance=ANN%OutlierMinDistance
      !IF (iprint1>0) THEN
      !   WRITE(UNIT=6,FMT='("Predicting from ANN for data point: [")',ADVANCE="NO")
      !   DO i=1,ndimensionsx
      !      WRITE(UNIT=6,FMT='(F3.0)',ADVANCE="NO") xdata(i)
      !   END DO
      !   WRITE(6,*) "]"
      !   WRITE(6,*) "Checking whether data point is outlier ..."
      !   WRITE(UNIT=6,FMT='(" ... Weights supplied:[")',ADVANCE="NO")
      !   DO j=1,ndimensionsx
      !      WRITE(UNIT=6,FMT='(ES15.3)',ADVANCE="NO") weights(j)
      !   END DO
      !   WRITE(UNIT=6,FMT='("]")')
      !END IF
      
      !check if all pairs in xdata have been included in the fitting of ANN
      !CorrelationNotConsidered=>ANN%CorrelationNotConsidered
      !DO i=1,ndimensionsx-1
      !   DO j=i+1,ndimensionsx
      !      IF (xdata(i)*xdata(j)/=0._dp .AND. CorrelationNotConsidered(i,j)) RETURN !data is outlier
      !   END DO
      !END DO
      
      !DO i=1,ndata
      !   distance=HammingDistance(xdata1(ndimensionsx*(i-1)+1:ndimensionsx*i),xdata,ndimensionsx,weights)
      !   distance1=HammingDistance(xdata1(ndimensionsx*(i-1)+1:ndimensionsx*i),xdata,ndimensionsx,weights1)
      !   IF (iprint1>0) THEN
      !      WRITE(UNIT=6,FMT='("[")',ADVANCE="NO")
      !      DO j=1,ndimensionsx
      !         WRITE(UNIT=6,FMT='(F3.0)',ADVANCE="NO") xdata1(ndimensionsx*(i-1)+j)
      !      END DO
      !      WRITE(UNIT=6,FMT='("] Distances 1 & 2:",2F15.5)') distance,distance1
      !   END IF
      !   !IF (distance<=OutlierMinDistance) THEN
      !   IF (distance<=OutlierMinDistance .AND. distance1<1.6_dp) THEN
      !      !Lets check how well current point from xdata1 was fitted...
      !      fdata_array=ANNOutput(ANN,xdata1(ndimensionsx*(i-1)+1:ndimensionsx*i),1,ndimensionsx)
      !      WRITE(6,*) " ...how well current point from xdata1 was fitted...",fdata_array,ANN%ydata(i)
      !      IF (ABS(fdata_array(1)-ANN%ydata(i))<0.05_dp) THEN
      !         DataIsOutlier=.FALSE.
!WRITE(UNIT=6,FMT='("Type any key to continue:")',ADVANCE="NO")
!READ(*,*) crapchar
      !         RETURN
      !      END IF
      !   END IF
      !END DO
!WRITE(UNIT=6,FMT='("Type any key to continue:")',ADVANCE="NO")
!READ(*,*) crapchar
   END FUNCTION DataIsOutlier
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE CreateANN(ANN,natoms,ndimensionsx,xdata,ydata,nmaxdata,ndata, &
      xdata_stored,ydata_stored,nmaxdata_stored,ndata_stored,ncritical_stored, &
      ftraining,ftesting,fvalidation,nneuronperlayer, &
      activationfunction,nlayers,OptimizationMode,OutlierMinDistance,iseed, &
      TrackCorrelations,iprint)
   !Creates a datastructure of type NeuralNet
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: ndata,natoms,ndimensionsx,nlayers,nmaxdata,nmaxdata_stored,ndata_stored,ncritical_stored
      REAL(dp), DIMENSION(ndimensionsx*nmaxdata), TARGET :: xdata
      REAL(dp), DIMENSION(nmaxdata), TARGET :: ydata
      REAL(dp), DIMENSION(ndimensionsx*nmaxdata_stored), TARGET, OPTIONAL :: xdata_stored
      REAL(dp), DIMENSION(nmaxdata_stored), TARGET, OPTIONAL :: ydata_stored
      INTEGER, DIMENSION(nlayers), TARGET :: nneuronperlayer
      INTEGER, DIMENSION(nlayers), TARGET :: activationfunction
      REAL(dp) :: ftraining,ftesting,fvalidation,OutlierMinDistance
      INTEGER :: OptimizationMode,iprint1,i,iseed
      INTEGER, OPTIONAL :: iprint
      LOGICAL :: TrackCorrelations
      
      IF (PRESENT(iprint)) THEN
         iprint1=iprint
      ELSE
         iprint1=1
      END IF
      
      IF (iprint1>0) WRITE(6,*) "Creating new ANN ..."
      IF (.NOT. ASSOCIATED(ANN)) THEN
         ALLOCATE(ANN)
         IF (iprint1>0) WRITE(6,*) " ... allocated space to ANN"
      END IF
      ANN%natoms=natoms
      ANN%ndimensionsx=ndimensionsx
      
      IF (natoms+(natoms*(natoms-1))/2/=ndimensionsx) THEN !assuming that only pair interactions are present
         WRITE(6,*) "Err>> Given the number of atoms the number of dimensions should have been different"
         STOP
      END IF
      
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... number of dimensions in control variable: ",I3)') ANN%ndimensionsx
      ANN%xdata=>xdata
      ANN%ydata=>ydata
      ANN%nmaxdata=nmaxdata
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... maximum amount of data in xdata: ",I6)') ANN%nmaxdata
      ANN%ndata=ndata
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... number of data points stored in xdata: ",I6)') ANN%ndata
      ANN%nmaxdata_stored=nmaxdata_stored
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... maximum data points to be stored in xdata_stored: ",I6)') &
         ANN%nmaxdata_stored
      IF (PRESENT(xdata_stored)) THEN
         ANN%xdata_stored=>xdata_stored
         IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... pointing xdata_stored to array provided")') 
      ELSE
         ALLOCATE(ANN%xdata_stored(ndimensionsx*nmaxdata_stored))
         IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... allocated space to xdata_stored: ",I7)') &
            ANN%ndimensionsx*ANN%nmaxdata_stored
      END IF
      IF (PRESENT(ydata_stored)) THEN
         ANN%ydata_stored=>ydata_stored
         IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... pointing ydata_stored to array provided")')
      ELSE
         ALLOCATE(ANN%ydata_stored(nmaxdata_stored))
         IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... allocated space to ydata_stored: ",I7)') ANN%nmaxdata_stored
      END IF
      
      ALLOCATE(ANN%xsignature(nmaxdata))
      ALLOCATE(ANN%xstoredsignature(nmaxdata_stored))
      
      ANN%ndata_stored=ndata_stored
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... current data points in ydata_stored: ",I6)') ANN%ndata_stored
      ANN%ncritical_stored=ncritical_stored
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... critical amount of data in stored arrays before training: ",I6)') &
         ncritical_stored
      ANN%ftraining=ftraining
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... training fraction: ",F15.6)') ANN%ftraining
      ANN%ftesting=ftesting
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... testing fraction: ",F15.6)') ANN%ftesting
      ANN%fvalidation=fvalidation
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... validation fraction: ",F15.6)') ANN%fvalidation
      ANN%nlayers=nlayers
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... number of layers in ANN: ",I2)') ANN%nlayers
      ANN%nneuronperlayer=>nneuronperlayer
      IF (iprint1>0) THEN
         WRITE(UNIT=6,FMT='("  ... number of neurons in each layer: ")',ADVANCE="NO")
         DO i=1,nlayers
            WRITE(UNIT=6,FMT='(I3)',ADVANCE="NO") ANN%nneuronperlayer(i)
         END DO
         WRITE(6,*) ""
      END IF
      ANN%activationfunction=>activationfunction
      IF (iprint1>0) THEN
         WRITE(UNIT=6,FMT='("  ... activation function in each layer in each layer: ")',ADVANCE="NO")
         DO i=1,nlayers
            WRITE(UNIT=6,FMT='(I3)',ADVANCE="NO") ANN%activationfunction(i)
         END DO
         WRITE(6,*) ""
      END IF
      ANN%OptimizationMode=OptimizationMode
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... optimization mode selected: ",I2)') ANN%OptimizationMode
      
      ANN%OutlierMinDistance=OutlierMinDistance
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... data is outlier when Hamming distance exceeds: ",F15.5)')  &
         ANN%OutlierMinDistance
      
      ANN%iseed=iseed
      IF (iprint1>0) WRITE(UNIT=6,FMT='("  ... random number generator seed for ANN: ",I6)') ANN%iseed
      
      IF (TrackCorrelations) THEN
         ANN%TrackCorrelations=.TRUE.
         ALLOCATE(ANN%CorrelationNotConsidered(natoms,natoms))
         ANN%CorrelationNotConsidered=.TRUE.
      END IF
      
      ALLOCATE(ANN%InteractionIsActive(ndimensionsx))
      ALLOCATE(ANN%InteractionCount(ndimensionsx))
      
      NULLIFY(ANN%xdata_selected)
      NULLIFY(ANN%ydata_selected)
      NULLIFY(ANN%fdata_selected)
      NULLIFY(ANN%datapurpose)
      NULLIFY(ANN%weights)
      IF (iprint1>0) WRITE(6,*) "Completed creation of ANN"
   END SUBROUTINE CreateANN
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE SelectData(ANN,purpose,iprint)
   !Collect data of purpose given by purpose
   !purpose can be for (1)training (2)testing or (3)validation
   !this data is stored in ydata_selected and xdata_selected of size nselected
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER, DIMENSION(:), POINTER :: datapurpose
      REAL(dp), DIMENSION(:), POINTER :: xdata,ydata,xdata_selected,ydata_selected
      INTEGER :: nselected,purpose,iselected,idata,ndata,ndimensionsx,iprint1
      INTEGER, OPTIONAL :: iprint
      
      IF (PRESENT(iprint)) THEN
         iprint1=iprint
      ELSE
         iprint1=1
      END IF
      
      IF (iprint1>0) THEN
         WRITE(UNIT=6,FMT='(" Transferring data into xdata_selected for purpose: ")',ADVANCE="NO")
         SELECT CASE(purpose)
         CASE(1); WRITE(6,*) "TRAINING"
         CASE(2); WRITE(6,*) "TESTING"
         CASE(3); WRITE(6,*) "VALIDATION"
         END SELECT
      END IF
      !--------------------------------------------------------------------
      !Initial checks and assigment of nselected
      ndimensionsx=ANN%ndimensionsx
      IF (ndimensionsx==0) THEN
         WRITE(6,*) "Err>> SelectData: Number of dimensions associated with input has to be provided"
         STOP
      END IF
      ndata=ANN%ndata
      IF (ndata==0) THEN
         WRITE(6,*) "Err>> SelectData: Number of input data points has to be provided"
         STOP
      END IF
      IF (ASSOCIATED(ANN%xdata)) THEN
         IF (ANN%ndata==0 .OR. SIZE(ANN%xdata)==0) THEN
            WRITE(6,*) "Err>> SelectData: Number of xdata points is zero"
            STOP
         END IF
      ELSE
         WRITE(6,*) "Err>> SelectData: Add xdata to ANN"
         STOP
      END IF
      IF (ASSOCIATED(ANN%ydata)) THEN
         IF (SIZE(ANN%ydata)==0) THEN
            WRITE(6,*) "Err>> SelectData: Number of ydata points is zero"
            STOP
         END IF
      ELSE
         WRITE(6,*) "Err>> SelectData: Add ysdata to ANN"
         STOP
      END IF
      
      SELECT CASE(purpose)
      CASE(1); nselected=ANN%ntraining
      CASE(2); nselected=ANN%ntesting
      CASE(3); nselected=ANN%nvalidation
      CASE DEFAULT
         WRITE(6,*) "Err>> SelectData: Type of data purpose unknown"
         STOP
      END SELECT
      IF (nselected==0) THEN
         WRITE(6,*) "Err>> SelectData: Original data has not been partitioned for ANN training/testing/validation"
         STOP
      !otherwise we can safely assume that datapurpose is also defined
      END IF
      ANN%nselected=nselected
      IF (ASSOCIATED(ANN%xdata_selected)) THEN
         IF (SIZE(ANN%xdata_selected)/=ndimensionsx*nselected) THEN
            DEALLOCATE(ANN%xdata_selected)
            ALLOCATE(ANN%xdata_selected(ndimensionsx*nselected))
         END IF
      ELSE
         ALLOCATE(ANN%xdata_selected(ndimensionsx*nselected))
      END IF
      IF (ASSOCIATED(ANN%ydata_selected)) THEN
         IF (SIZE(ANN%ydata_selected)/=nselected) THEN
            DEALLOCATE(ANN%ydata_selected)
            ALLOCATE(ANN%ydata_selected(nselected))
         END IF
      ELSE
         ALLOCATE(ANN%ydata_selected(nselected))
      END IF
      IF (ASSOCIATED(ANN%fdata_selected)) THEN
         IF (SIZE(ANN%fdata_selected)/=nselected) THEN
            DEALLOCATE(ANN%fdata_selected)
            ALLOCATE(ANN%fdata_selected(nselected))
         END IF
      ELSE
         ALLOCATE(ANN%fdata_selected(nselected))
      END IF
      IF (iprint1>0) THEN
         WRITE(UNIT=6,FMT='(" ... xdata_selected has size: ",I6)') ndimensionsx*nselected
         WRITE(UNIT=6,FMT='(" ... ydata_selected has size: ",I6)') nselected
         WRITE(UNIT=6,FMT='(" ... fdata_selected has size: ",I6)') nselected
      END IF
      xdata_selected=>ANN%xdata_selected
      ydata_selected=>ANN%ydata_selected
      xdata=>ANN%xdata
      ydata=>ANN%ydata
      datapurpose=>ANN%datapurpose
      
      !--------------------------------------------------------------------
      !Now fill the data of type datapurpose into xdata_selectde and ydata_selected
      iselected=0
      DO idata=1,ndata
         !WRITE(*,*) idata,datapurpose(idata)
         IF (datapurpose(idata)==purpose) THEN !this gets selected
            iselected=iselected+1

            ydata_selected(iselected)=ydata(idata)
            xdata_selected((iselected-1)*ndimensionsx+1:iselected*ndimensionsx)= &
               xdata((idata-1)*ndimensionsx+1:idata*ndimensionsx)
            !WRITE(*,*) iselected
         END IF
      END DO
      IF (iprint1>0) WRITE(6,*) "Transferred data into xdata_selected"
   END SUBROUTINE SelectData
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION ANNOutput(ANN,xdata,ndata,ndimensionsx)
   !weights,nweights,nbias,nneuronperlayer,nlayers,activationfunction)
   !Finds the output from ANN for the weights provided in the network
   !xdata is the raw input
   !nweights is the number of weights in the ANN
   !nbias is the number of bias in the ANN
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: ilayer,nlayers,ndata,ndimensionsx,nweights,nbias,activationfunction
      REAL(dp), DIMENSION(:), TARGET :: xdata
      REAL(dp), DIMENSION(:), POINTER :: weights
      INTEGER, DIMENSION(:), POINTER :: nneuronperlayer
      REAL(dp), DIMENSION(ndata) :: ANNOutput
      
      !Allocatable arrays
      REAL(dp), DIMENSION(:), POINTER :: LayerInput,LayerOutput,weights1,bias1
      !Used for layer calculations
      INTEGER :: nneurons1,nweights1,nbias1,ndata1,ndimx1
      INTEGER :: iweightmin,iweightmax,ibiasmin,ibiasmax
      
      ANNOutput=0._dp
      weights=>ANN%weights
      nweights=ANN%nweights
      nbias=ANN%nbias
      nlayers=ANN%nlayers
      nneuronperlayer=>ANN%nneuronperlayer
      
      LayerInput=>xdata(1:ndimensionsx*ndata)
      ndata1=ndata
      
      !Find range of the weight vector that needs to be used
      iweightmin=1
      ibiasmin=nweights+1
      ndimx1=ndimensionsx
      
      DO ilayer=1,nlayers
         activationfunction=ANN%activationfunction(ilayer)
         nneurons1=nneuronperlayer(ilayer)
         nweights1=nneurons1*ndimx1 !number of weights in this layer
         iweightmax=iweightmin-1+nweights1
         nbias1=nneurons1 !number of bias in this layer
         ibiasmax=ibiasmin-1+nbias1
         weights1=>weights(iweightmin:iweightmax)
         bias1=>weights(ibiasmin:ibiasmax)
         ALLOCATE(LayerOutput(nneurons1*ndata))
         CALL ANNLayerOutput(LayerInput,ndimx1,ndata1,weights1,nweights1,bias1,nbias1, &
            nneurons1,activationfunction,LayerOutput)
         
         !Setup the input/output arrays
         IF (ilayer>1) DEALLOCATE(LayerInput)
         LayerInput=>LayerOutput
         NULLIFY(LayerOutput)
         
         ndimx1=nneurons1
         iweightmin=iweightmax+1
         ibiasmin=ibiasmax+1
      END DO
      
      ANNOutput(1:ndata)=LayerInput(1:ndata)
      DEALLOCATE(LayerInput) !release the memory
   END FUNCTION ANNOutput
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE ANNLayerOutput(xdata,ndimensionsx,ndata,weights,nweights,bias,nbias, &
      nneurons,activationfunction,output)
   !Purpose of this routine: finds the output from a single layer of ANN
   !xdata is the input data (1D array of size ndimensionsx*ndata)
   !ndimensionx is the dimensionality of the input to a single neuron
   !ndata is the number of data points in x
   !weights is the weights for each of the neurons in the layer i (1D array of size ndimensions*nneuronperlayer(i))
   ! in the raw form it is provided as transpose of [w(1,1) w(1,2) ....  w(1,m) w(2,1) w(2,2) ....  w(2,m) ..... w(n,1) w(n,2) ....  w(n,m)]
   !nweights is the size of weights array
   !bias is the bias for the neurons in this layer
   !nbias is the size of the bias array
   !nneurons is the number of neurons in the layer
   !activationfunction is an integer corresponding to the type of activation function to be used
   !output is the output from the single layer (1D array of size nneurons*ndata)
      IMPLICIT NONE
      INTEGER :: ndimensionsx,ndata,nweights,nbias,nneurons
      REAL(dp), DIMENSION(ndimensionsx*ndata) :: xdata
      REAL(dp), DIMENSION(nweights) :: weights
      REAL(dp), DIMENSION(nbias) :: bias
      REAL(dp), DIMENSION(nneurons*ndata) :: output
      INTEGER :: activationfunction,imin,imax,idata
      
      !Find dot product of weight matrix and input matrix
      output=PACK(MATMUL( & !pack the result into a 1D column
         RESHAPE(weights,shape=(/nneurons,ndimensionsx/),order=(/2,1/)), & !each row contains the weights for a neuron
         RESHAPE(xdata,shape=(/ndimensionsx,ndata/))), & !each column corresponds to a data point
         MASK=.TRUE.)
         
      !Add the weights
      imin=1
      imax=nbias
      DO idata=1,ndata
         output(imin:imax)=output(imin:imax)+bias(1:nbias)
         imin=imax+1
         imax=imax+nbias
      END DO
      !Activation function
      SELECT CASE (activationfunction)
      CASE(1) !LogSigmoidal
         output=LogSigmoidal(output,nneurons*ndata)
      CASE(2) !TanSigmoidal
         output=TanSigmoidal(output,nneurons*ndata)
      CASE(3) !PurelyLinear
         output=PureLinear(output,nneurons*ndata)
      CASE(4) !user defined
         output=UserFunction(output,nneurons*ndata)
      CASE DEFAULT
         WRITE(6,*) "Err>> This type of activation function is not defined:",activationfunction
         STOP
      END SELECT
   END SUBROUTINE ANNLayerOutput    
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE FindSizeWeightsArray(ANN,iprint)
   !Finds the size of the weight vector by computing nweights and nbias using 
   !  ndimensionsx, nneuronperlayer and nlayers
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: nlayers,ndimx,nneurons
      INTEGER, DIMENSION(:), POINTER :: nneuronperlayer
      INTEGER :: ilayer,nweights,nbias,iprint1
      INTEGER, OPTIONAL :: iprint
      
      IF (PRESENT(iprint)) THEN
         iprint1=iprint
      ELSE
         iprint1=1
      END IF
      
      ndimx=ANN%ndimensionsx
      IF (ndimx==0) THEN
         WRITE(6,*) "Err>> ndimensionsx in FindSizeWeightsArray is zero"
         STOP
      END IF
      nlayers=ANN%nlayers
      IF (nlayers==0) THEN
         WRITE(6,*) "Err>> nlayers in FindSizeWeightsArray is zero"
         STOP
      END IF
      nneuronperlayer=>ANN%nneuronperlayer
      IF (ASSOCIATED(ANN%nneuronperlayer)) THEN
         IF (SIZE(nneuronperlayer)/=nlayers) THEN
            WRITE(6,*) "Err>> Number of layers and size of nneuronperlayer are incompatible in FindSizeWeightsArray"
            STOP
         END IF
      ELSE
         WRITE(6,*) "Err>> nneuronperlayer is not associated in FindSizeWeightsArray"
         STOP
      END IF
      
      nweights=0
      nbias=0
      DO ilayer=1,nlayers
         nneurons=nneuronperlayer(ilayer)
         IF (nneurons<=0 .OR. nneurons>MaxNeuronPerLayer) THEN
            WRITE(6,*) "Err>> nneurons in FindSizeWeightsArray is out of bounds:",nneurons
            STOP
         END IF
         nweights=nweights+nneurons*ndimx
         nbias=nbias+nneurons
         ndimx=nneurons !this is the dimensionality of the new layer
      END DO
      ANN%nweights=nweights
      ANN%nbias=nbias
      IF (iprint1>0) THEN
         WRITE(6,*) "Creating weights array ..."
         WRITE(UNIT=6,FMT='(" ... number of weights in ANN: ",I4)') ANN%nweights
         WRITE(UNIT=6,FMT='(" ... number of biases in ANN: ",I4)') ANN%nbias
      END IF
      CALL MakeSizeANNWeights(ANN,nweights+nbias)
   END SUBROUTINE FindSizeWeightsArray
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE MakeSizeANNWeights(ANN,nweightsbias,iprint)
   !creates weights array of size nweights+nbias
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: nweightsbias,iprint1
      INTEGER, OPTIONAL :: iprint
      
      IF (PRESENT(iprint)) THEN
         iprint1=iprint
      ELSE
         iprint1=1
      END IF
      
      IF (ASSOCIATED(ANN%weights)) THEN
         IF (SIZE(ANN%weights)/=nweightsbias) THEN
            DEALLOCATE(ANN%weights)
            ALLOCATE(ANN%weights(nweightsbias))
            ANN%weights=0._dp
            IF (iprint1>0) WRITE(UNIT=6,FMT='(" ... size of weight array: ",I4)') nweightsbias
         END IF
      ELSE
         ALLOCATE(ANN%weights(nweightsbias))
         ANN%weights=0._dp
         IF (iprint1>0) WRITE(UNIT=6,FMT='(" ... size of weight array: ",I4)') nweightsbias
      END IF
   END SUBROUTINE MakeSizeANNWeights
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE PartitionANNData(ANN,iprint)
   !finds the values of ntraining, ntesting and nvalidation
   !fills the array datapurpose with a number 1, 2 or 3 
   ! 1: training data
   ! 2: testing data
   ! 3: validation data
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: ndata,ntraining,ntesting,nvalidation
      INTEGER, DIMENSION(:), POINTER :: datapurpose
      REAL(dp) :: ftraining,ftesting,fvalidation,rand1
      INTEGER :: idata1,idata,value,iprint1
      INTEGER, OPTIONAL :: iprint
      
      IF (PRESENT(iprint)) THEN
         iprint1=iprint
      ELSE
         iprint1=1
      END IF
      
      ndata=ANN%ndata
      IF (ndata==0) THEN
         WRITE(6,*) "Number of data points stored in ANN is zero"
         STOP
      END IF
      ftraining=ANN%ftraining
      ftesting=ANN%ftesting
      fvalidation=ANN%fvalidation
      IF (ftraining<=0._dp .OR. ftesting<=0._dp .OR. fvalidation<=0._dp) THEN
         WRITE(6,*) "Err>> Fraction of data for training, testing and validation not specified in PartitionANNData"
         STOP
      END IF
      ntraining=CEILING(REAL(ndata)*ftraining)
      nvalidation=FLOOR(REAL(ndata)*fvalidation)
      ntesting=ndata-ntraining-nvalidation
      ANN%ntraining=ntraining
      ANN%ntesting=ntesting
      ANN%nvalidation=nvalidation
      IF (iprint1>0) THEN
         WRITE(UNIT=6,FMT='(" Partitioning data into following sets ... ")')
         WRITE(UNIT=6,FMT='(" ... Training: ",I4)') ntraining
         WRITE(UNIT=6,FMT='(" ... Testing: ",I4)') ntesting
         WRITE(UNIT=6,FMT='(" ... Validation: ",I4)') nvalidation
      END IF
      
      IF (ASSOCIATED(ANN%datapurpose)) THEN
         IF (SIZE(ANN%datapurpose)/=ndata) THEN
            DEALLOCATE(ANN%datapurpose)
            ALLOCATE(ANN%datapurpose(ndata))
            IF (iprint1>0) WRITE(UNIT=6,FMT='(" ... creating datapurpose array of size: ",I6)') ndata
         END IF
      ELSE
         ALLOCATE(ANN%datapurpose(ndata))
         IF (iprint1>0) WRITE(UNIT=6,FMT='(" ... creating datapurpose array of size: ",I6)') ndata
      END IF
      datapurpose=>ANN%datapurpose
      
      !now choose the set randomly
      datapurpose(1:ntraining)=1
      datapurpose(ntraining+1:ntraining+ntesting)=2
      datapurpose(ntraining+ntesting+1:ndata)=3
      DO idata=1,ndata
         rand1=taus88()
         idata1=CEILING(rand1*REAL(ndata))
         value=datapurpose(idata)
         datapurpose(idata)=datapurpose(idata1)
         datapurpose(idata1)=value
      END DO
      IF (iprint1>0) WRITE(UNIT=6,FMT='(" Completed partitioning of data")')
      
   END SUBROUTINE PartitionANNData
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE InitializeANNWeights(ANN,iseed)
   !initializes the weights of ANN
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: nweights,nbias,iweight,iseed1
      REAL(dp), DIMENSION(:), POINTER :: weights
      REAL(dp) :: randomv
      INTEGER, OPTIONAL :: iseed
      
      IF (PRESENT(iseed)) THEN
         iseed1=iseed
      ELSE
         iseed1=ANN%iseed
      END IF
      
      IF (ANN%nweights==0 .OR. ANN%nbias==0) THEN
         CALL FindSizeWeightsArray(ANN)
      END IF
      IF (ASSOCIATED(ANN%weights)) THEN
         IF (SIZE(ANN%weights)/=ANN%nweights+ANN%nbias) CALL FindSizeWeightsArray(ANN)
      ELSE
         CALL FindSizeWeightsArray(ANN)
      END IF
      
      nweights=ANN%nweights
      nbias=ANN%nbias
      weights=>ANN%weights
      CALL InitializeTaus88(iseed1)
      DO iweight=1,nweights
         weights(iweight)=taus88()
         !write(*,*) weights(iweight)
      END DO
   END SUBROUTINE InitializeANNWeights
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE OptimizeANN(ANN)
   !Optimizes the weights of ANN
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER :: nweights,nbias
      REAL(dp) :: fret,ftol,gtol,xtol,SclFac
      INTEGER :: iter,omode,i,j
      REAL(dp), DIMENSION(2*ANN%nweightsactive+ANN%nbias) :: weights !factor of two arises because of symmetry constraints
      INTEGER :: errorstatus,ITMAX
      
      nweights=ANN%nweights
      nbias=ANN%nbias
      IF (nweights==0 .OR. nbias==0) THEN
         WRITE(6,*) "Err>> Number of weights/bias is zero in OptimizeANN"
         STOP
      END IF
      omode=ANN%OptimizationMode
      weights=0._dp !ANN%weights
      
      !IF (ASSOCIATED(weights)) THEN
      !   IF (SIZE(weights)/=nweights+nbias) THEN
      !      WRITE(6,*) "Err>> Size of weights array is incompatible with nweights and nbias in OptimizeANN"
      !      STOP
      !   END IF
      !ELSE
      !   WRITE(6,*) "Err>> Weights are not associated in OptimizeANN"
      !END IF
      
      ActiveNeuralNet=>ANN
      
      SELECT CASE(omode)
      CASE(1) !steepest descent
         SclFac=0.01_dp !to be used for scaling forces
         ftol=1.0e-9_dp
         gtol=2.0e-6_dp
         xtol=1.0e-5_dp
         CALL SteepestDescent(weights,ftol,gtol,xtol,iter,fret,ANNError,ANNErrorGradient, &
            dx=0.00001_dp,ITMAX=ITMAX,IsPrint1=.TRUE.,errorstatus=errorstatus)
      CASE(2) !conjugate gradient
         SclFac=0.01_dp
         ftol=1.0e-9_dp !this should come from potential
         gtol=2.0e-6_dp
         xtol=1.0e-5_dp
         CALL ConjugateGradient(weights,ftol,gtol,xtol,iter,fret,ANNError,ANNErrorGradient, &
            dx=0.0001_dp,ITMAX=ITMAX,IsPrint1=.TRUE.,errorstatus=errorstatus)
      CASE(3) !LBFGS
         ftol=1.0e-9_dp
         gtol=2.0e-3_dp
         xtol=1.0e-5_dp
         ITMAX=200
         CALL Lbfgs(weights,ftol,gtol,xtol,iter,fret,ANNError,ANNErrorGradient, &
              IsPrint1=.TRUE.,ITMAX=ITMAX,errorstatus=errorstatus)
      !CASE(4) !dynamical Euler
         !CALL 
      !CASE(5) !Runge Kutta
      !CASE(6) !QuickMin
      !CASE(7) !FIRE
      CASE(8) !DFP
         !ftol=1.0e-9_dp
         !gtol=2.0e-6_dp
         !xtol=1.0e-5_dp
         CALL DFP(weights,ftol,gtol,xtol,iter,fret,ANNError,ANNErrorGradient, &
            IsPrint1=.TRUE.,errorstatus=errorstatus)
      CASE DEFAULT
         WRITE(6,*) "Error>> Optimization type is not known to OptimizeANN"
         STOP
      END SELECT
      WRITE(6,*) "Optimized weights:"
      j=0
      ActiveNeuralNet%weights=0._dp
      DO i=1,ActiveNeuralNet%nweights
         IF (ActiveNeuralNet%InteractionIsActive(i)) THEN
            j=j+1
            ActiveNeuralNet%weights(i)=weights(j)
         END IF
      END DO
      DO i=ActiveNeuralNet%nweights+1,ActiveNeuralNet%nweights+ActiveNeuralNet%nbias
         j=j+1
         ActiveNeuralNet%weights(i)=weights(j)
      END DO
      DO i=1,ANN%nweights+ANN%nbias
         WRITE(6,*) ANN%weights(i)
      END DO
   END SUBROUTINE OptimizeANN
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION ANNError(x,errorstatus)
   !x corresponds to the weights
   !ydata,xdata,ndimensionsx,ndata,weights,nweights,nbias,nneuronperlayer,nlayers,activationfunction
   !Obtains the error given the ydata, xdata and the weights
   !ANN is the weighted norm
   !ndata is the number of data points used in finding the error
      IMPLICIT NONE
      INTEGER :: activationfunction,nselected
      !REAL(dp), DIMENSION(:), POINTER :: fdata_selected
      REAL(dp), DIMENSION(:), INTENT(IN) :: x
      REAL(dp) :: ANNError
      INTEGER :: i,j,i1,errorstatus
      
      errorstatus=0
      
      j=0
      ActiveNeuralNet%weights=0._dp
      DO i=1,ActiveNeuralNet%nweights
         IF (ActiveNeuralNet%InteractionIsActive(i)) THEN
            j=j+1
            ActiveNeuralNet%weights(i)=x(j)
         END IF
      END DO
      DO i=ActiveNeuralNet%nweights+1,ActiveNeuralNet%nweights+ActiveNeuralNet%nbias
         j=j+1
         ActiveNeuralNet%weights(i)=x(j)
      END DO
      !ActiveNeuralNet%weights=x
      
      nselected=ActiveNeuralNet%nselected
      !fdata_selected=>ActiveNeuralNet%fdata_selected
      ActiveNeuralNet%fdata_selected=ANNOutput(ActiveNeuralNet, &
         ActiveNeuralNet%xdata_selected, &
         ActiveNeuralNet%nselected,ActiveNeuralNet%ndimensionsx)
       
      ANNError=0._dp
      ANNError=SUM((ActiveNeuralNet%fdata_selected(1:nselected)- &
         ActiveNeuralNet%ydata_selected(1:nselected))* &
         (ActiveNeuralNet%fdata_selected(1:nselected)- &
         ActiveNeuralNet%ydata_selected(1:nselected)))

      !symmetry constraints using Lagrange multipliers
      DO i=1,ActiveNeuralNet%nweights
         IF (ActiveNeuralNet%InteractionIsActive(i)) THEN
            j=j+1
            i1=ActiveNeuralNet%SymmMap(i)
            ANNError=ANNError+x(j)*(ActiveNeuralNet%weights(i)-ActiveNeuralNet%weights(i1))**2 !penalize if symmetry is not obeyed
         END IF
      END DO
   END FUNCTION ANNError
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION ANNErrorGradient(x,errorstatus)
   !Gives the gradient with respect to the weights
      IMPLICIT NONE
      REAL(dp), DIMENSION(:), INTENT(IN) :: x
      REAL(dp), DIMENSION(SIZE(x)) :: weights
      REAL(dp), DIMENSION(SIZE(x)) :: ANNErrorGradient
      REAL(dp) :: ANNError0,ANNError1,dweight
      INTEGER :: iweight,errorstatus
      
      ANNErrorGradient=0._dp
      weights=x
      dweight=0.0001_dp
      ANNError0=ANNError(weights,errorstatus)
      DO iweight=1,ActiveNeuralNet%nweightsactive+ActiveNeuralNet%nbias
         weights(iweight)=weights(iweight)+dweight
         ANNError1=ANNError(weights,errorstatus)
         ANNErrorGradient(iweight)=(ANNError1-ANNError0)/dweight
         !WRITE(6,*) ANNError1,ANNError0,ANNErrorGradient(iweight)
         weights(iweight)=weights(iweight)-dweight
      END DO
      !WRITE(6,*) "Completed gradient calculation"
      
   END FUNCTION ANNErrorGradient
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   SUBROUTINE AddSymmetryConstraints(ANN)
   !SymmetryConstraints is an array holding indices which can provide symmetry info
   !presently this works for 2mm symmetry - 2-fold mirror symmetry
   !e.g., SymmetryConstraints(i)=SymmetryConstraints(n-i+1)
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER, PARAMETER :: nsites=28 !these many sites are present
      INTEGER, DIMENSION(nsites) :: map
      INTEGER, DIMENSION(nsites+(nsites*(nsites-1))/2+(nsites*(nsites-1)*(nsites-2))/6), TARGET :: SymmMap !assume 3-way interactions
      INTEGER :: indx,i,j,k,i1,j1,k1,mi,mj,mk
      
      
      map=(/23,24,25,26,27,28,17,18,19,20,21,22,13,14,15,16,7,8,9,10,11,12,1,2,3,4,5,6/) !for site i, map(i) is the symmetric location
      !this is created for nsites=28
      indx=0
      !one-way interactions
      DO i=1,nsites 
         indx=indx+1
         SymmMap(i)=map(i)
      END DO
      !two-way interactions
      DO i=1,nsites-1
         mi=map(i)
         DO j=i+1,nsites
            indx=indx+1
            mj=map(j)
            i1=MIN(mi,mj) !smaller of the two
            j1=MAX(mi,mj) !larger of the two
            SymmMap(indx)=nsites*i1-(i1*(i1-1))/2+j1-i1
            !there are nsites from one-way interaction & 2-way: nsites-1 + nsites-2 + ... + nsites-(i1-1) + j1-i1
            !hence nsites+ nsites*(i1-1) - (1+2+...+(i1-1)) + j1-i1
         END DO
      END DO
      !three-way interactions
      DO i=1,nsites-2
         mi=map(i)
         DO j=i+1,nsites-1
            mj=map(j)
            DO k=j+1,nsites
               indx=indx+1
               mk=map(k)
               i1=min(min(mi,mj),mk)
               k1=max(max(mi,mj),mk)
               j1=mi+mj+mk-i1-k1
               SymmMap(indx)=nsites+(nsites*(nsites-1))/2
               SymmMap(indx)=SymmMap(indx)+((6*nsites*(nsites-1)+(2*i1-1)*i1-3*(2*nsites-1)*i1)*(i1-1))/12
               SymmMap(indx)=SymmMap(indx)+((nsites-i1-1)*(nsites-i1))/2-((nsites-j1)*(nsites-j1+1))/2
               SymmMap(indx)=SymmMap(indx)+k1-j1
            END DO
         END DO
      END DO
      
      ANN%SymmMap=>SymmMap
   END SUBROUTINE AddSymmetryConstraints
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION LogSigmoidal(x,n)
   !Purpose of this routine:
      IMPLICIT NONE
      INTEGER :: n
      REAL(dp), DIMENSION(n) :: x,LogSigmoidal
      
      WHERE (x>12._dp)
         LogSigmoidal=1._dp
      ELSEWHERE (x<-18._dp)
         LogSigmoidal=0._dp
      ELSEWHERE
         LogSigmoidal=1._dp/(1._dp+exp(-x))
      END WHERE
   END FUNCTION LogSigmoidal
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION TanSigmoidal(x,n)
   !Purpose of this routine:
      IMPLICIT NONE
      INTEGER :: n
      REAL(dp), DIMENSION(n) :: x,TanSigmoidal
      
      TanSigmoidal=2._dp/(1._dp+exp(-2._dp*x))-1._dp
   END FUNCTION TanSigmoidal
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION PureLinear(x,n)
   !Purpose of this routine:
      IMPLICIT NONE
      INTEGER :: n
      REAL(dp), DIMENSION(n) :: x,PureLinear
      
      PureLinear=x
   END FUNCTION PureLinear
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION UserFunction(x,n)
   !Purpose of this routine:
      IMPLICIT NONE
      INTEGER :: n
      REAL(dp), DIMENSION(n) :: x,UserFunction
      
      UserFunction=0._dp
   END FUNCTION UserFunction
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   !Supposed to work with ANN for (100) systems
   !Find how many times the interaction is switched on
   !If interaction is switch on for enough times then do a fit
   SUBROUTINE GetActiveInteractions(ANN)
   !find interactions that are important - these are interactions with large weight
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      INTEGER, DIMENSION(:), POINTER :: InteractionCount
      LOGICAL, DIMENSION(:), POINTER :: InteractionIsActive=>NULL()
      REAL(dp), DIMENSION(:), POINTER :: xdata=>NULL()
      REAL(dp), DIMENSION(ANN%ndimensionsx) :: xdata1
      INTEGER :: idata,nweights,i,ndimensionsx
      
      InteractionIsActive=>ANN%InteractionIsActive
      InteractionCount=>ANN%InteractionCount
      
      !check how many times an interaction is switched on
      xdata=>ANN%xdata_selected
      InteractionCount=0
      ndimensionsx=ANN%ndimensionsx
      DO idata=1,ANN%nselected
         xdata1=xdata(ndimensionsx*(idata-1)+1:ndimensionsx*idata)
         DO i=1,ndimensionsx
            IF (xdata1(i)/=0._dp) InteractionCount(i)=InteractionCount(i)+1
         END DO
      END DO
      
      !if interaction is on more than 2 times and off more than 2 times then it is active
      InteractionIsActive=.FALSE.
      nweights=0
      DO i=1,ndimensionsx
         InteractionIsActive(i)=InteractionCount(i)>0 .AND. InteractionCount(i)<ANN%nselected
         IF (InteractionIsActive(i)) nweights=nweights+1
      END DO
      ANN%nweightsactive=nweights
      WRITE(6,*) "Number of active interactions:",nweights
      
      !now modify the size of the weight array and train for active interactions
   END SUBROUTINE GetActiveInteractions
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
   FUNCTION EliminatedWeakInteractions(ANN,ecut)
      IMPLICIT NONE
      TYPE(NeuralNet), POINTER :: ANN
      REAL(dp) :: ecut
      LOGICAL :: EliminatedWeakInteractions
      INTEGER :: i
      
      EliminatedWeakInteractions=.FALSE.
      DO i=1,ANN%ndimensionsx
         IF (ABS(ANN%weights(i))<ecut .AND. ABS(ANN%weights(i))>0._dp) THEN
            WRITE(*,*) "Ignoring interaction #",i
            ANN%InteractionIsActive(i)=.FALSE.
            EliminatedWeakInteractions=.TRUE.
            ANN%weights(i)=0._dp
            ANN%nweightsactive=ANN%nweightsactive-1
         END IF
      END DO
   END FUNCTION EliminatedWeakInteractions
   !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
END MODULE ANNModule

